// Generated by CoffeeScript 1.10.0
(function() {
  var injectContentScripts;

  injectContentScripts = function() {
    var content_scripts, i, insertLocation, j, len, len1, manifest, ref, results, script, scriptElement, scriptInfo, style, styleElement;
    manifest = chrome.runtime.getManifest();
    content_scripts = manifest.content_scripts;
    insertLocation = document.head.firstChild;
    results = [];
    for (i = 0, len = content_scripts.length; i < len; i++) {
      scriptInfo = content_scripts[i];
      if (scriptInfo.matches.indexOf("<all_urls>") === -1) {
        continue;
      }
      if (scriptInfo.js) {
        ref = scriptInfo.js;
        for (j = 0, len1 = ref.length; j < len1; j++) {
          script = ref[j];
          scriptElement = document.createElement("script");
          scriptElement.type = "text/javascript";
          scriptElement.async = false;
          scriptElement.src = chrome.runtime.getURL(script);
          insertLocation.parentElement.insertBefore(scriptElement, insertLocation);
        }
      }
      if (scriptInfo.css) {
        results.push((function() {
          var k, len2, ref1, results1;
          ref1 = scriptInfo.css;
          results1 = [];
          for (k = 0, len2 = ref1.length; k < len2; k++) {
            style = ref1[k];
            styleElement = document.createElement("link");
            styleElement.rel = "stylesheet";
            styleElement.type = "text/css";
            styleElement.href = chrome.runtime.getURL(style);
            results1.push(insertLocation.parentElement.insertBefore(styleElement, insertLocation));
          }
          return results1;
        })());
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  injectContentScripts();

}).call(this);
