#!/bin/bash

value=0

if [[ $1 == "-init" ]]; then
    echo "50" > /tmp/actual_brightness
else
    runcount=$(ps -aux | grep volnoti | wc -l)
    if [ $runcount -lt 2 ]; then
        volnoti -a 0.9 -t 2 -r 20
    fi

    if [[ $1 -gt 0 ]]; then
        actual=$(cat /tmp/actual_brightness)
        if [[ $actual -lt 10 ]]; then
            actual=10
        else
            actual=$(($actual+10))
        fi
        if [[ $actual -gt 100 ]]; then
            actual=100
        fi
        volnoti-show -s ~/.scripts/resources/brightness.png $actual &
        echo "$actual" > /tmp/actual_brightness
        value=$actual
    elif [[ $1 -lt 0 ]]; then
        actual=$(cat /tmp/actual_brightness)
        if [[ $actual -le 10 ]]; then
            actual=$(($actual-1))
        else
            actual=$(($actual-10))
        fi
        if [[ $actual -lt 0 ]]; then
            actual=0
        fi
        volnoti-show -s ~/.scripts/resources/brightness.png $actual &
        echo "$actual" > /tmp/actual_brightness
        value=$actual
    elif [[ $1 == "dim" ]]; then
        echo "10" > /tmp/actual_brightness
        value=10
    else
        volnoti-show -s ~/.scripts/resources/brightness.png 50 &
        echo "50" > /tmp/actual_brightness
        value=50
    fi
    # lego_refresh "brightness"
    xbacklight -set $value
fi
