#!/bin/bash

if [[ $1 == "-init" ]]; then
    echo "50" > /tmp/current_volume
    pactl set-sink-volume 0 50%
elif [[ $1 == '-mute' ]]; then
    pactl set-sink-mute 0 toggle

    if [[ -f /tmp/mute_val ]]; then
        volnoti-show $(cat /tmp/mute_val) &> /dev/null
        cat /tmp/mute_val > /tmp/current_volume
        rm /tmp/mute_val
    else
        cat /tmp/current_volume > /tmp/mute_val
        volnoti-show -m &> /dev/null
    fi

    runcount=$(ps -aux | grep volnoti | wc -l)
    if [ $runcount -lt 2 ]; then
        volnoti -a 0.9 -t 2 -r 20
    fi
else
    if [[ -f /tmp/mute_val ]]; then
        current_volume=$(cat /tmp/mute_val)
        rm /tmp/mute_val
        pactl set-sink-mute 0 toggle
    else
        current_volume=$(cat /tmp/current_volume)
    fi
    current_volume=$(($current_volume+$1))
    if [[ $current_volume -le 0 ]]; then
        current_volume=0
    fi
    # notify-send -t 2000 "Volume" "$current_volume%" --icon=dialog-information

    runcount=$(ps -aux | grep volnoti | wc -l)
    if [ $runcount -lt 2 ]; then
        volnoti -a 0.9 -t 2 -r 20
    fi
    volnoti-show $current_volume &> /dev/null
    echo "$current_volume" > /tmp/current_volume
    current_volume=$(echo "$current_volume%")
    pactl set-sink-volume 0 $current_volume
fi
lego_refresh "volume"
