#!/bin/bash
MPV_HISTORY=/home/infiniter/.local/share/qutebrowser/mpv_history
SEPARATOR="##@@##@@##"

store_history(){
    TITLE=$(youtube-dl -e "$QUTE_URL")
    echo "$TITLE $SEPARATOR $QUTE_URL" >> "$MPV_HISTORY"
}

store_history &

mpv "$QUTE_URL"
