#!/bin/sh

MPV_HISTORY="$HOME/.local/share/mpv_history/history"
SEPARATOR="##@@##@@##"

[ -f "$MPV_HISTORY" ] \
    || ( mkdir -p $(dirname "$MPV_HISTORY") && touch "$MPV_HISTORY" )

store_history(){
    TITLE=$(youtube-dl -e "$QUTE_URL")
    echo "$TITLE $SEPARATOR $QUTE_URL" >> "$MPV_HISTORY"
}

store_history &

mpv "$QUTE_URL"
