git:
  paging:
    colorArg: always
    pager: delta -s --dark --paging=never --24-bit-color=never --syntax-theme=base16

gui:
  sidePanelWidth: 0.15 # gives you more space to show things side-by-side
  border: "rounded"
  theme:
    selectedLineBgColor:
      - black
  theme:
    activeBorderColor:
      - "#f5a97f"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#f5a97f"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"

  authorColors:
    "*": "#b7bdf8"
