git:
  paging:
    colorArg: always
    pager: delta -s --dark --paging=never --24-bit-color=never --syntax-theme=base16

gui:
  sidePanelWidth: 0.15 # gives you more space to show things side-by-side
  border: "rounded"
  theme:
    selectedLineBgColor:
      - black
