customCommands:
  - key: '<c-t>'
    context: 'localBranches'
    command: 'nvim -c "DiffviewOpen {{.SelectedLocalBranch.Name}}...{{.CheckedOutBranch.Name}} -- ."'
    description: 'Open Diffview against selected branch'
    output: terminal

git:
  pagers:
    - colorArg: always
      pager: "delta -s --dark --paging=never --true-color=always --syntax-theme=gruvbox-dark --minus-style='syntax #4a2b33' --minus-emph-style='syntax #653744' --plus-style='syntax #2f4733' --plus-emph-style='syntax #3f5f43' --line-numbers-minus-style='#f08a9a' --line-numbers-plus-style='#9ed98f'"
gui:
  sidePanelWidth: 0.15 # gives you more space to show things side-by-side
  border: "rounded"
  theme:
    activeBorderColor:
      - "#f5a97f"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#f5a97f"
    unstagedChangesColor:
      - "#f08a9a"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"
  authorColors:
    "*": "#b7bdf8"
