#!/bin/bash

[[ ! -d /usr/share/subtube ]] \
    && echo -en " " \
    && exit 1
news=$(ls /usr/share/subtube/resources/thumbnails | wc -l)
q=$(cat /usr/share/subtube/resources/subtube_queue | wc -l)
queue=""
if [[ $q -gt 0 ]]; then
    queue="($q)"
fi

if [[ $news -gt 0 ]] || [[ $q -gt 0 ]]; then
    echo -en " $news$queue"
else
    echo -en " empty"
fi
