model = "gpt-6-astra"
model_reasoning_effort = "high"
# Computer-use cleanup is handled by the unified-computer-use plugin hooks.
approvals_reviewer = "auto_review"
service_tier = "default"

notify = ["/Users/Viktor/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/Viktor/Code/sensory-minds"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/sensory-minds/hdplusbusinessengine"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/sensory-minds/hdplusbusinessenginegui"]
trust_level = "trusted"

[projects."/Users/Viktor/.claude"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/sensory-minds/website-relaunch-2026"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/sensory-minds/hdplusjwtserver"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/nix-on-droid"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/ai_image_edit"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/warehouse"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/nix-darwin"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/nix-server"]
trust_level = "trusted"

[projects."/Users/Viktor/.config/helix"]
trust_level = "trusted"

[projects."/Users/Viktor/.dots"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-18/gi"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-19/new-chat"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/cvicenie"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-22/wri"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-22/write-me-email-to-getfit-explaining"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-22/exp"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-23/wh"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-23/br"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-23/spi"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-23/nee"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-24/how"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-24/worl"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-24/fin"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-25/realtime-voice-chat"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-25/realtime-voice-chat-2"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-25/realtime-voice-chat-3"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-25/use"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-25/wh"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-26/wire"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-26/com"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-27/ger"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/sensory-minds"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-27/what"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-27/find"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-27/i-w"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/booking_scraper"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-28/ger"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-28/find"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-28/i-w"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-29/e"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-29/fin"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-29/dock"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-29/es"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-29/wha"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-30/ger"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-30/can"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-31/some"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-31/i-w"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-07-31/ver"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-01/my"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-03/exp"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-03/wha"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-04/rich"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-04/how"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/sensory-minds/metzler-website-relaunch-2026"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-04/find"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-04/ge"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-04/i-ha"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/glab-pipelines"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-07/p5"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-07/laska-kraska"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-08/at"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-09/heu"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-09/how"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-10/som"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-10/how"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-10/dep"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-10/in"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-11/find"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-11/ger"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-11/tr"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-11/lo"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-12/dock"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-12/ge"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-12/whe"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-12/sim"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-14/1-mongodb-2026-08-14t07-12"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-14/hel"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-14/ex"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-15/wh"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-16/in"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-16/cor"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/fitness-tracker"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-16/the"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-16/i"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-16/c"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-17/show"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-17/do"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-18/git"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-18/if"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-18/ger"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/lk-revenue/dashboard"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-18/how-t"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-20/my"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-20/my-2"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-20/tra"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-21/pay"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-21/i-l"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-21/realtime-voice-chat"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-21/the"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-21/i-w"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-22/why"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-22/what"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-23/wha"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-24/ger"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-24/what"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/ai-usage"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-25/how-d"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-25/does"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-25/tell"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-26/ger"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-26/explain-to-me-reason-for-lambda"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-26/in"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-26/dock"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-27/ger"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-27/gi"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-28/wha"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-28/mer"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-28/wor"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-28/bash-x20"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-28/ex"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-28/in-x20"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/fitness-ai"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-30/drez-s-excentrom-meaning"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-30/find"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-31/gene"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-31/find"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-08-31/what"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-01/new-chat"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-01/how-x20"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-01/for"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/personal 2"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-02/realtime-voice-chat"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-02/realtime-voice-chat-2"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/mongo-backup"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/natos_cv"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-07/i-have-opened"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-07/whe"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-08/is-r"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-08/use-x20"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-08/i-x20"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-08/i-x20-2"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-09/use-x20"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-09/wr"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-09/get"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/vite-portfolio"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-09/realtime-voice-chat"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-09/th"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-10/chro"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-10/hel"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-10/is-t"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-11/hel"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-11/whe"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-11/use-computer-use-and-create-for"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-11/sta"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-11/how-x20"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-11/how-do-i-install-t3code-on"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-11/how-x20-2"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/stuff"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/nixzero-scripts"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-12/how-do-i-fork-a-conversation"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-12/create-an-image-of"]
trust_level = "trusted"

[projects."/Users/Viktor/.scripts"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/3d"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/caffeinate-gui"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-15/f"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-16/the"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-17/new-chat"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/sensory-minds/agentic_speech_demo"]
trust_level = "trusted"

[projects."/Users/Viktor/Documents/Codex/2026-09-17/you-x20"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/conversation"]
trust_level = "trusted"

[projects."/Users/Viktor/Code/file-relay"]
trust_level = "trusted"

[tui]
theme = "gruvbox-dark"

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4
gpt-6-astra = 4

[plugins."github@openai-curated"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[features]
hooks = true
js_repl = false

[hooks.state]

[hooks.state."/Users/Viktor/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:28c8bc3aac34a901bdb8bd802fd2821b1192352c35e98427384f32856d4ff9bc"

[hooks.state."/Users/Viktor/.codex/hooks.json:permission_request:0:0"]
trusted_hash = "sha256:474013e4741a75970463c980bf92fb8cfa65929b95ea330abf3e077d2d9911b1"

[hooks.state."/Users/Viktor/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:6ec7c45272bd652b6d55233bcdb3a60fc8134c029bc585ce1018be607c91805b"

[desktop]
followUpQueueMode = "queue"
realtimeVoiceScreenContextEnabled = true
conversationDetailMode = "STEPS_COMMANDS"

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/Viktor/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/Viktor/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/Viktor/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
CODEX_HOME = "/Users/Viktor/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.917.51856"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/Users/Viktor/.codex/plugins/cache/openai-bundled/browser/26.917.51856/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_SERVICE_PATH = "/Users/Viktor/.codex/computer-use/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[mcp_servers.youtrack]
command = "npx"
args = ["-y", "mcp-remote", "https://agile.sensory-minds.com/mcp", "--header", "Authorization:${YOUTRACK_AUTH}", "--transport", "http-only"]

[mcp_servers.youtrack.env]
YOUTRACK_AUTH = "Bearer perm-di5uYWd5.NTgtNTg=.bH10LkLvCrnsizIUFsZbyIqStcfkmM"

[shell_environment_policy.set]
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "9230e2bd8b24b7ac7a0ba6774c64bf0d78ecdabbdd91d0ed627b02a587bae2df"
