#!/bin/bash

chosen=$(echo -e "Power OFF\nHibernate\nReboot\nLock" | dmenu -theme /usr/share/rofi/themes/bye.rasi)
echo $chosen
if [[ $chosen = 'Power OFF' ]]; then
    systemctl poweroff
elif [[ $chosen = 'Hibernate' ]]; then
    systemctl hibernate
elif [[ $chosen = 'Reboot' ]]; then
    reboot
elif [[ $chosen = 'Lock' ]]; then
    inactivity_lock
else
    echo 'Doing nothing.'
fi
