#!/bin/sh

size=$(df -P | grep /dev/nvme | awk '{sum += $2} END {print sum}')
used=$(df -P | grep /dev/nvme | awk '{sum += $3} END {print sum}')
available=$(df -P | grep /dev/nvme | awk '{sum += $4} END {print sum}')
percentage=$(python -c "print(int($used/$available*100))")
notify-send -i 'none' 'Disk usage' "$percentage%"
