#!/bin/bash

if [[ $1 == '-focused' ]]; then
    scrot --focused ~/Pictures/Screenshots/temporary_screen.png
elif [[ $1 == '-zone' ]]; then
    maim -u -s ~/Pictures/Screenshots/temporary_screen.png
elif [[ $1 == '-save' ]]; then
    scrot ~/screenshot_$(date '+%Y-%m-%d_%H:%M').png
else
    maim ~/Pictures/Screenshots/temporary_screen.png
fi
xclip -selection clipboard -t image/png -i ~/Pictures/Screenshots/temporary_screen.png
rm ~/Pictures/Screenshots/temporary_screen.png
