#!/bin/bash

if [[ $1 == "--reverse" ]]; then
    numerated=$(cat ~/.config/sxhkd/sxhkdrc | nl -b a | sed '1,8d' | sed '/^\s*#[^#]+/d' | sed -n '/###/{n;p;}')
    raw=$(echo "$numerated" | sed 's/\s*[0-9]*\s*//')
    option=$(echo "$raw" | dmenu -i -p "Show behavior for given binding")
    [[ -z $option ]] && exit 1
    bind_line=$(echo "$numerated" | sed -n "/\s*$option\s*$/p" | awk '{print $1}')
    comment_line=$(($bind_line-1))
    comment=$(cat ~/.config/sxhkd/sxhkdrc | sed -n "${comment_line}p" | sed 's/###\s*//')
    notify-send -t 5000 "$option" "$comment" -i "none"
else
    numerated=$(cat ~/.config/sxhkd/sxhkdrc | nl -b a | sed '1,8d' | grep "###" | sed 's/\s*###//' | sed 's/\s*//')
    raw=$(echo "$numerated" | sed 's/[0-9]*\s*//')
    option=$(echo "$raw" | dmenu -i -p "Show binding for given behavior")
    [[ -z $option ]] && exit
    comment_line=$(echo "$numerated" | grep "$option" | awk '{print $1}')
    echo "comment_line" $comment_line
    binding_line=$((comment_line+1))
    binding=$(cat ~/.config/sxhkd/sxhkdrc | sed -n "${binding_line}p")
    notify-send -t 5000 "$option" "$binding" -i "none"
fi
