#!/bin/sh

ICON="~/.scripts/resources/battery.png"

while true;
do
    status=$(acpi -b | grep 'Battery 0' | awk '{ print $3 }' | sed 's/[^a-zA-Z]\+//')
    if [[ $status != 'Discharging' ]]; then
        echo 100 > /tmp/battery_val
        sleep 60
        continue
    fi
    perc=$(acpi -b | grep 'Battery 0' | awk '{ print $4 }' | sed 's/%,//')

    if [[ ! -f /tmp/battery_val ]]; then
        echo $perc > /tmp/battery_val
    fi

    old=$(cat /tmp/battery_val)
    if [[ $old -gt $perc ]]; then
        if [[ $perc -le 1 && $old -gt 1 ]]; then
            notify-send -u critical -i $ICON -t 2000 'Battery' '1% remaining'
        elif [[ $perc -le 2 && $old -gt 2 ]]; then
            notify-send -u critical -i $ICON -t 2000 'Battery' '2% remaining'
        elif [[ $perc -le 3 && $old -gt 3 ]]; then
            notify-send -u critical -i $ICON -t 2000 'Battery' '3% remaining'
        elif [[ $perc -le 4 && $old -gt 4 ]]; then
            notify-send -u critical -i $ICON -t 2000 'Battery' '4% remaining'
        elif [[ $perc -le 5 && $old -gt 5 ]]; then
            notify-send -u critical -i $ICON -t 2000 'Battery' '5% remaining'
        elif [[ $perc -le 10 && $old -gt 10 ]]; then
            notify-send -u critical -i $ICON -t 2000 'Battery' '10% remaining'
        elif [[ $perc -le 15 && $old -gt 15 ]]; then
            notify-send -i $ICON -t 2000 'Battery' '15% remaining'
        elif [[ $perc -le 20 && $old -gt 20 ]]; then
            notify-send -i $ICON -t 2000 'Battery' '20% remaining'
        elif [[ $perc -le 30 && $old -gt 30 ]]; then
            notify-send -i $ICON -t 2000 'Battery' '30% remaining'
        elif [[ $perc -le 50 && $old -gt 50 ]]; then
            notify-send -i $ICON -t 2000 'Battery' '50% remaining'
        elif [[ $perc -le 60 && $old -gt 60 ]]; then
            notify-send -i $ICON -t 2000 'Battery' '60% remaining'
        elif [[ $perc -le 70 && $old -gt 70 ]]; then
            notify-send -i $ICON -t 2000 'Battery' '70% remaining'
        elif [[ $perc -le 80 && $old -gt 80 ]]; then
            notify-send -i $ICON -t 2000 'Battery' '80% remaining'
        elif [[ $perc -le 90 && $old -gt 90 ]]; then
            notify-send -i $ICON -t 2000 'Battery' '90% remaining'
        fi
    fi
    # lego_refresh "battery"
    echo $perc > /tmp/battery_val
    sleep 30
done
