#!/bin/bash


if [[ $# -eq 0 ]]; then
    options="quad\nthesis\nmasters_coding"
    chosen=$( echo -e $options | dmenu -i -p 'Choose layout:')
    if [[ $chosen != '' ]]; then
        notify-send "Layout" "chosen layout: $chosen"
        layout_creator $chosen
    fi
else
    bspc desktop -f $(bspc query -D -d .\!occupied | sed 1q)
    case $1 in
        'thesis')
            alacritty --working-directory /home/infiniter/Diplomka/latex/thesis/ &
            zathura /home/infiniter/Diplomka/latex/thesis/main.pdf &
            ;;
        'masters_coding')
            alacritty --working-directory /home/infiniter/Diplomka &
            alacritty --working-directory /home/infiniter/Diplomka &
            ;;
        'quad')
            alacritty &
            alacritty &
            alacritty &
            # bspc rule -a Alacritty split_ratio=0.5 --one-shot; \
            bspc node -p south -o 0.45
            alacritty &
            ;;
        *)
            echo 'unknown'
            ;;
    esac
fi
