#!/bin/bash

if [[ ! -f /tmp/pymonocle ]]; then
    echo 'monocle_on' > /tmp/pymonocle
else
    status=$(cat /tmp/pymonocle)
    if [[ $status == 'monocle_on' ]]; then
        echo 'monocle_off' > /tmp/pymonocle
    else
        echo 'monocle_on' > /tmp/pymonocle
    fi
fi
