#!/bin/bash

files=$(ls ~/Downloads | grep -e 'pdf\|png\|jpg\|jpeg\|gif')

choice=$(echo "$files" | dmenu -i -p 'Choose file to open')

if [[ ! -z $choice ]]; then
    if [[ $choice == *.pdf ]]; then
        zathura ~/Downloads/$choice
    elif [[ $choice == *.png ]] || [[ $choice == *.jpg ]] || [[ $choice == *.jpeg ]] || [[ $choice == *.gif ]]; then
        sxiv ~/Downloads/$choice
    fi
fi
