#!/bin/bash

if [[ ! -d /tmp/tabber ]]; then
    mkdir /tmp/tabber
fi
if [[ $1 == '-init' ]]; then
    mkdir /tmp/tabber
elif [[ $1 == '-show' ]]; then
    bspc rule -a Sxiv state=floating rectangle=710+500+500+300 --one-shot;
    sxiv -b -t -o /tmp/tabber | xargs rm
elif [[ $1 == '-clear' ]]; then
    rm /tmp/tabber/*
fi
