#!/bin/bash

runcount=$(ps -aux | grep transmission-daemon | wc -l)
if [ $runcount -gt 1 ]; then
    for i in ~/Downloads/*.torrent; do
        [ -f "$i" ] || break
        transmission-remote -a "$i"
        rm "$i"
        sleep 1
    done
else
    transmission-daemon &
    echo "Turning transmission-daemon ON...run again"
fi
torrent_notifier &
