#!/bin/bash


if [[ ! -f /tmp/actual_brightness ]]; then
    res=$(printf " %.0f" $(xbacklight -get))
else
    res=$(printf " %.0f" $(cat /tmp/actual_brightness))
fi
echo -ne "%{F#F9DC2b}$res%{F-}"
