#!/bin/bash

news=$(ls ~/.scripts/resources/thumbnails | wc -l)
q=$(cat ~/.scripts/resources/subtube_queue | wc -l)
queue=""
if [[ $q -gt 0 ]]; then
    queue="($q)"
fi

if [[ $news -gt 0 ]] || [[ $q -gt 0 ]]; then
    echo -en " $news$queue"
fi
